# Generated by Django 4.2.16 on 2024-09-14 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(default=datetime.datetime(2024, 9, 14, 22, 52, 43, 112082, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
