# Generated by Django 4.2.16 on 2024-09-19 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_categories_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 18, 26, 43, 753773, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
