# Generated by Django 4.2.16 on 2024-09-19 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 19, 45, 25, 171494, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
