# Generated by Django 4.2.16 on 2024-09-17 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-created'], 'verbose_name': 'red social', 'verbose_name_plural': 'redes sociales'},
        ),
    ]
